### PR TITLE
Add "matrix_benchmarks" command

### PR DESCRIPTION
**Pull request by kpouget**
This PR adds a "matrix_benchmarks" command to the `ci-dashboard`.

This new commands generate output  files (in `output/matrix_benchmarks/`) properly structured for parsing&plotting with the MatrixBenchmark tool (see this [PR](https://gitlab.com/kpouget_psap/matrix_benchmark/-/merge_requests/2))

Here is an example of the current plot done by the MatrixBenchmark, via the interactive interface:
image

### CODE REVIEW

**Comment by kpouget** [comment]
Hello @jmencak, could you please have quick look at this PR (most important is the part *outside* of `cmd/matrix_benchmarks/*.go`)

It is mostly a refactoring of the code to make them easier to reuse, in particular with `populate.TraverseAllTestResults` which traverses all the tests and triggers a callback on all of them.

Generation test passes: https://github.com/openshift-psap/ci-dashboard/pull/21/checks?check_run_id=3190498688

**Comment by kpouget** [comment]
> Hello @jmencak, could you please have quick look at this PR (most important is the part _outside_ of `cmd/matrix_benchmarks/*.go`)
> 
> It is mostly a refactoring of the code to make them easier to reuse, in particular with `populate.TraverseAllTestResults` which traverses all the tests and triggers a callback on all of them.
> 
> Generation test passes: https://github.com/openshift-psap/ci-dashboard/pull/21/checks?check_run_id=3190498688

Hello @jmencak @omertuc , could you have a quick look at this PR, 
and maybe this one, https://github.com/openshift-psap/ci-dashboard/pull/29, which adds 3 commits on top of https://github.com/openshift-psap/ci-dashboard/pull/21.
PR https://github.com/openshift-psap/ci-dashboard/pull/29 is relevant for all the dashboards, while https://github.com/openshift-psap/ci-dashboard/pull/21 is mostly a refactoring + a new command for the plotting on-going work.

**Comment by jmencak** [comment]
Thank you for the PR, Kevin.  This PR is an improvement towards "structured development".  Tested this PR and it seems to work fine.
However, this warning should be fixed before merging:
```
$ go vet ./...
# github.com/openshift-psap/ci-dashboard/pkg/populate
pkg/populate/populate.go:65:4: github.com/openshift-psap/ci-dashboard/api/matrix/v1.ToolboxStepResult composite literal uses unkeyed fields
```

**Comment by kpouget** [comment]
> Thank you for the PR, Kevin. This PR is an improvement towards "structured development". Tested this PR and it seems to work fine.
> However, this warning should be fixed before merging:
> 
> ```
> $ go vet ./...
> # github.com/openshift-psap/ci-dashboard/pkg/populate
> pkg/populate/populate.go:65:4: github.com/openshift-psap/ci-dashboard/api/matrix/v1.ToolboxStepResult composite literal uses unkeyed fields
> ```

thanks @jmencak , I'll make sure to follow `go vet` reports, I didn't really know it could be useful!

fixed with:
https://github.com/openshift-psap/ci-dashboard/compare/d8dd1f0fb735e0df3e86070ebf192f3f4585fa7f..bac46c22e90d69b9e80f9e24d2c7cee29dfa6e48

(I understand that's it's not recommended to instantiate objects with `type{value}` instead of `type{field: value}`), I didn't notice that before!

**Comment by jmencak** [comment]
Thank you for the PR and the changes, Kevin!

/lgtm

**Comment by kpouget** [comment]
thanks @jmencak, really appreciated :)

merging and rebasing https://github.com/openshift-psap/ci-dashboard/pull/29.

**Pull request merged**
